# Generated by Django 3.1.3 on 2020-11-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_mlhmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='commits_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
