# Generated by Django 3.1.3 on 2020-11-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_project_commits_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLHCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('commit_url', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
