# Generated by Django 3.1.3 on 2020-11-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_mlhcommit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MLHCommit',
            new_name='Commit',
        ),
    ]
